/* spellchecker: disable */

export const domains = process.env.LINK_SHORTENER_DOMAINS?.split(',') ?? [];

// Note: new-post.sh expects this object to be at the end of the file to
//       add new posts to the list.
export const REDIRECTS: Record<string, string> = {
    // Socials
    github: 'https://github.com/ceiphr',
    gh: 'https://github.com/ceiphr',
    linkedin: 'https://www.linkedin.com/in/ari/',

    // Referrals
    do: 'https://m.do.co/c/b95c2a8a5568',

    // Projects
    dotfiles: 'https://github.com/ceiphr/dotfiles',

    // Articles
    hthypdp:
        'https://www.digitalocean.com/community/tutorials/how-to-harden-your-production-django-project',
    '2PcYE4L':
        'https://www.digitalocean.com/community/tutorials/how-to-display-data-from-the-digitalocean-api-with-django',
    accid: 'https://ceiphr.com/a-crash-course-in-django/',

    /* BELOW REDIRECTS ARE GENERATED BY new-post.sh - DO NOT REMOVE OR MODIFY */
    '4acf87e': 'https://ceiphr.com/beveled-corners-with-sass/',
    '95e4365': 'https://ceiphr.com/blog/example-post/'
};
