import fs from 'fs';
import Head from 'next/head';
import Link from 'next/link';
import path from 'path';

import matter from 'gray-matter';

import Layout from '@components/Layout';
import { POSTS_PATH, postFilePaths } from '@utils/mdx';

const METADATA = {
    title: 'Blog',
    description: 'A list of blog posts'
};

interface Props {
    posts: Post[];
}

export default function Index({ posts }: Props) {
    return (
        <>
            <Head>
                <title>{METADATA.title}</title>
                <meta name="description" content={METADATA.description} />
                <meta
                    property="twitter:image"
                    content={`https://${process.env.NEXT_PUBLIC_DOMAIN}/api/og?title=${METADATA.title}`}
                />
                <meta property="twitter:card" content="summary_large_image" />
                <meta property="twitter:title" content={METADATA.title} />
                <meta
                    property="twitter:description"
                    content={METADATA.description}
                />
                <meta
                    property="og:image"
                    content={`https://${process.env.NEXT_PUBLIC_DOMAIN}/api/og?title=${METADATA.title}`}
                />
                <meta property="og:title" content={METADATA.title} />
                <meta
                    property="og:description"
                    content={METADATA.description}
                />
                <meta
                    property="og:url"
                    content={`https://${process.env.NEXT_PUBLIC_DOMAIN}/blog`}
                />
            </Head>
            <Layout>
                <main>
                    <h1>Blog</h1>
                    <p>
                        Click the link below to navigate to a page generated by{' '}
                        <code>next-mdx-remote</code>.
                    </p>
                    <ul>
                        {posts.map((post) => (
                            <li key={post.filePath}>
                                <Link
                                    as={`/blog/${post.filePath.replace(
                                        /\.mdx?$/,
                                        ''
                                    )}`}
                                    href={`/blog/[slug]`}
                                >
                                    {post.data.title}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </main>
            </Layout>
        </>
    );
}

export function getStaticProps() {
    const posts = postFilePaths.map((filePath): Post => {
        const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath
        };
    });

    return { props: { posts } };
}
