import fs from 'fs';
import Head from 'next/head';
import Link from 'next/link';
import path from 'path';

import matter from 'gray-matter';

import Layout from '@components/Layout';
import { POSTS_PATH, postFilePaths } from '@utils/mdx';

interface Props {
    posts: Post[];
}

export default function Index({ posts }: Props) {
    return (
        <>
            <Head>
                <title>Blog</title>
            </Head>
            <Layout>
                <main>
                    <h1>Blog</h1>
                    <p>
                        Click the link below to navigate to a page generated by{' '}
                        <code>next-mdx-remote</code>.
                    </p>
                    <ul>
                        {posts.map((post) => (
                            <li key={post.filePath}>
                                <Link
                                    as={`/blog/${post.filePath.replace(
                                        /\.mdx?$/,
                                        ''
                                    )}`}
                                    href={`/blog/[slug]`}
                                >
                                    {post.data.title}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </main>
            </Layout>
        </>
    );
}

export function getStaticProps() {
    const posts = postFilePaths.map((filePath): Post => {
        const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
        const { content, data } = matter(source);

        return {
            content,
            data,
            filePath
        };
    });

    return { props: { posts } };
}
